### ISSUE TITLE
ERROR: 'variables'

### ISSUE THREAD

**Issue by cage1016** [giovannicoppola/i-sheet-you-not#2]
```bash
[13:40:41.712] ERROR: I Sheet You Not[Run Script] Building workflow "d" in /Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8 ...
args=Namespace(bundle_id='net.deanishe.alfred-i-sheet-you-not.c3ac3c91318a45d8b5aa6bf06cbc0e6d', clean=True, dir='/Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8', name='d', random=True, force=True, open=True, debug=False, docpath='/Users/kaichuchung/tmp/a.xlsx', target="/Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/d-b'0.4'.alfredworkflow")
cd /Users/kaichuchung/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2FA61EB5-0844-4F8C-AC06-C456B2CA0D21/.
Copying workflow contents to /Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.62578 ...
Updating info.plist ...
cd /Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.62578
bundleid='net.deanishe.alfred-i-sheet-you-not.c3ac3c91318a45d8b5aa6bf06cbc0e6d'
name='d'
Deleting /Users/kaichuchung/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.62578...
ERROR: 'variables'
```

![CleanShot 2023-02-07 at 13 44 00@2x](https://user-images.githubusercontent.com/678607/217158705-d65c9cce-bcc3-4aa4-942e-3007e0c00162.jpg)

No idea about this error message.

**Comment by giovannicoppola** [comment]
do you have special characters in the file name? I see `d-b'0.4'.alfredworkflow`?
it seems it's failing to update the `info.plist` file.

**Comment by cage1016** [comment]
https://github.com/giovannicoppola/i-sheet-you-not/blob/50f73d9b39d7d9707385a855488315ad4c00dbf8/src/buildme#L246-L255

No, try and error few times and as above code show, ONLY input `d` variable to generated filename `d-b'0.4'.alfredworkflow`

**Comment by UUAMike** [comment]
I'm not sure how OP fixed their issue, but I am getting the same error. I am naming the workflow 'TEST' and get the following in the debug log.

I'll also note that this works properly in v0.4, but with this version I do not get any configuration options: 
<img width="1185" alt="image" src="https://github.com/giovannicoppola/i-sheet-you-not/assets/29314039/e3139c5b-87c5-4bb2-b797-de35024e3817">


14:00:00.849] I Sheet You Not[File Filter] Processing complete
[14:00:00.850] I Sheet You Not[File Filter] Passing output '/Users/michael/Library/CloudStorage/OneDrive-AM/#Query References/GHP Global Formulary.xlsx' to Arg and Vars
[14:00:00.850] I Sheet You Not[Arg and Vars] Processing complete
[14:00:00.851] I Sheet You Not[Arg and Vars] Passing output '' to Keyword
[14:00:05.108] I Sheet You Not[Keyword] Processing complete
[14:00:05.109] I Sheet You Not[Keyword] Passing output 'TEST' to Run Script
[14:00:05.666] ERROR: I Sheet You Not[Run Script] Building workflow "TEST" in /Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8 ...
args=Namespace(bundle_id='net.deanishe.alfred-i-sheet-you-not.d866acb3349542e5b8bf35e6c689a6c6', clean=True, dir='/Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8', name='TEST', random=True, force=True, open=True, debug=False, docpath='~/Library/CloudStorage/OneDrive-AM/#Query References/GHP Global Formulary.xlsx', target="/Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/TEST-b'0.4'.alfredworkflow")
cd /Users/michael/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A019816E-515A-4853-9958-21486C3CA83C/.
Copying workflow contents to /Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.1537 ...
Updating info.plist ...
cd /Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.1537
bundleid='net.deanishe.alfred-i-sheet-you-not.d866acb3349542e5b8bf35e6c689a6c6'
name='TEST'
Deleting /Users/michael/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.6e000a6551be46c682a0af7803c305e8/isyn.build.1537...
ERROR: 'variables'

**Comment by giovannicoppola** [comment]
I see a `#` in your path, have you tried to remove (or place the file somewhere else without `#`)?

**Comment by UUAMike** [comment]
> I see a `#` in your path, have you tried to remove (or place the file somewhere else without `#`)?

I just removed the '#' from the folder name, but still get the "ERROR: 'variables'"

**Comment by giovannicoppola** [comment]
I think the problem with the OP had to do with file name or path. if the excel file can be shared I can try to troubleshoot

**Comment by UUAMike** [comment]
Trying to simplify things to understand the issue... I created a new workbook with value of '1' in A1 and '2' in B2. Still getting the same error:

![image](https://github.com/giovannicoppola/i-sheet-you-not/assets/29314039/479bdd92-da6e-498f-8393-e7db84bfae31)

[Book1.xlsx](https://github.com/giovannicoppola/i-sheet-you-not/files/11926700/Book1.xlsx)

**Comment by giovannicoppola** [comment]
you are right, I can reproduce. and you were saying it is working with version 0.4?

**Comment by UUAMike** [comment]
> you are right, I can reproduce. and you were saying it is working with version 0.4?

I was working for me in 0.4 a day ago... now it's exhibiting a strange behavior where I can successfully create a workflow, but now nothing appears in the configuration options. Can't even add a keyword to run the workflow.

<img width="1116" alt="image" src="https://github.com/giovannicoppola/i-sheet-you-not/assets/29314039/76829860-b7c0-474b-9306-de017bf20f36">

**Comment by giovannicoppola** [comment]
in the older version, you can access the old 'environment variables' clicking on `Configure Workflow and variables`
![alfred_prefs](https://github.com/giovannicoppola/i-sheet-you-not/assets/5774411/1833c4a8-a612-46c4-ad92-4588d1df457c)
then clicking on `Environment Variables` you can set the variables, instructions [here](https://www.deanishe.net/i-sheet-you-not/#configuration).

I will check and try to fix the error, but it might take me a while... thanks for reporting

**Comment by giovannicoppola** [comment]
@UUAMike @cage1016 this should be fixed in the most recent [release](https://github.com/giovannicoppola/i-sheet-you-not/releases/latest). 

@UUAMike please note that your demo file should have data in at least 3 columns if you want to use the default settings - the first column (A) contains the result title, the second (B) its subtitle, and the third (C) contains the value.

Also, please remember to set the path to your excel file in the newly created workflow. Not sure this was needed in previous versions, but it is needed now. 

Let me know if you see anything off!
